spring.application.name=RATING-SERVICE
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/rating_db}

server.port=8081

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
